language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


  #before_script:
  # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Alone"
  - git config user.email "gary@cn-face.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://$token@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/zhouxianjun/zhouxianjun.github.io.git
